insert into `mdi_sub_location`
(
	`location_id`,
	`sub_location_uid`,
	`sub_location_name`,
	`sub_location_desc`,
	`sub_location_building`,
	`sub_location_floor`,
	`sub_location_room`,
	`is_deleted`,
	`org_id`,
	`created_by`,
	`created_on`,
	`modified_by`,
	`modified_on`
)
values
(
	@LocationId,
	@SubLocationUid,
	@SubLocationName,
	@SubLocationDesc,
	@SubLocationBuilding,
	@SubLocationFloor,
	@SubLocationRoom,
	@isDeleted,
	@OrganizationId,
	@ModifiedBy,
	current_timestamp(),
	@ModifiedBy,
	current_timestamp()
)